apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-claim
  namespace: container-registry
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: microk8s-hostpath
