apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  ARGOCD_SERVER: <server_IP_and_PORT>
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
  ARGOCD_USERNAME: <username-in-base64>
  ARGOCD_PASSWORD: <password-in-base64>
---
