apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: svc-tekton-{{ .Values.projectName }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "pods", "daemonsets"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["*"]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
