apiVersion: v1
kind: Secret
metadata:
  name: tekton-git-credentials-{{ .Values.projectName }}
  annotations:
    tekton.dev/git-0: github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
     -----END OPENSSH PRIVATE KEY-----
