apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  targetNamespace: tekton-pipelines
  profile: all
  chain:
    disabled: false
  pipeline:
    disable-affinity-assistant: false
    disable-creds-init: false
    enable-api-fields: alpha
    enable-custom-tasks: false
    enable-tekton-oci-bundles: false
    metrics.pipelinerun.duration-type: histogram
    metrics.pipelinerun.level: pipelinerun
    metrics.taskrun.duration-type: histogram
    metrics.taskrun.level: taskrun
    require-git-ssh-secret-known-hosts: false
    running-in-environment-with-injected-sidecars: false
    trusted-resources-verification-no-match-policy: ignore
    performance:
      disable-ha: false
      buckets: 1
      replicas: 3
      threads-per-controller: 32
      kube-api-qps: 100
      kube-api-burst: 200
  pruner:
    disabled: false
    schedule: "0 * * * *" 
    resources:
      - pipelinerun
      - taskrun
    keep: 3
    # keep-since: 1440
    # NOTE: you can use either "keep" or "keep-since", not both
    prune-per-resource: true
  hub:
    params:
      - name: enable-devconsole-integration
        value: "true"
  dashboard:
    readonly: false
