apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: woovi-ops-dev
  source:
    repoURL: git@github.com:woovibr/woovi-k8s-dev.git
    path: deployments/k8s-root-app
    targetRevision: HEAD
