apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-list-source
  namespace: {{ .Values.projectName }}
spec:
  workspaces:
    - name: source
  steps:
    - name: list
      image: ubuntu
      workingDir: $(workspaces.source.path)
      script: >
        ls
